name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # O 'main' se hai rinominato la branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Portfolio Dependencies
        run: npm install

      - name: Build Portfolio
        run: npm run build

      - name: Install Quartz Dependencies
        run: |
          cd notes
          npm install

      - name: Build Quartz
        run: |
          cd notes
          npx quartz build --output ../dist/notes

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
